In [1]:
import pandas as pd
import pickle

In [2]:
with open("modele_logreg.pkl", "rb") as f:
    modele = pickle.load(f)

print("Modèle chargé avec succès.")

Modèle chargé avec succès.

In [3]:
df_prod = pd.read_csv("billets_production.csv", sep=",")
df_prod.head()

   diagonal  height_left  height_right  margin_low  margin_up  length   id
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5

In [4]:
# Colonnes attendues par le pipeline (celles vues pendant l'entraînement)
colonnes_modele = list(modele.feature_names_in_)
print("Colonnes attendues par le modèle :", colonnes_modele)

print("\nColonnes du fichier production :", list(df_prod.columns))

Colonnes attendues par le modèle : ['diagonal', 'height_left', 'height_right', 'margin_low', 'margin_up', 'length']

Colonnes du fichier production : ['diagonal', 'height_left', 'height_right', 'margin_low', 'margin_up', 'length', 'id']

In [5]:
df_prod_vf = df_prod.drop(columns=['id'])
print("\nColonnes du fichier production_vf :", list(df_prod_vf.columns))

Colonnes du fichier production_vf : ['diagonal', 'height_left', 'height_right', 'margin_low', 'margin_up', 'length']

In [6]:
y_pred_modele = modele.predict(df_prod_vf)
print(y_pred_modele)

[False False False  True  True]

In [7]:
resultat = pd.DataFrame([False, False, False, True, True], columns=['resultat'])
resultat

   resultat
0     False
1     False
2     False
3      True
4      True

In [8]:
pd.concat([df_prod, resultat], axis=1)

,diagonal,height_left,height_right,margin_low,margin_up,length,id,resultat
0,171.76,104.01,103.54,5.21,3.30,111.42,A_1,False
1,171.87,104.17,104.13,6.00,3.31,112.09,A_2,False
2,172.00,104.58,104.29,4.99,3.39,111.57,A_3,False
3,172.49,104.55,104.34,4.44,3.03,113.20,A_4,True
4,171.65,103.63,103.56,3.77,3.16,113.33,A_5,True

In [9]:
def detect_faux_billets(dataset):
    df_prod_vf = dataset.drop(columns=['id'])
    y_pred_modele = modele.predict(df_prod_vf)
    resultat = pd.DataFrame(pd.Series(y_pred_modele), columns=['resultat'])
    resultat_vf = pd.concat([df_prod, resultat], axis=1)
    return resultat_vf

In [10]:
detect_faux_billets(df_prod)

,diagonal,height_left,height_right,margin_low,margin_up,length,id,resultat
0,171.76,104.01,103.54,5.21,3.30,111.42,A_1,False
1,171.87,104.17,104.13,6.00,3.31,112.09,A_2,False
2,172.00,104.58,104.29,4.99,3.39,111.57,A_3,False
3,172.49,104.55,104.34,4.44,3.03,113.20,A_4,True
4,171.65,103.63,103.56,3.77,3.16,113.33,A_5,True

In [11]:
#Autre fichier à tester
df_test = pd.read_csv("billets_production.csv", sep=",")
df_test.head()

   diagonal  height_left  height_right  margin_low  margin_up  length   id
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5

In [12]:
detect_faux_billets(df_test)

,diagonal,height_left,height_right,margin_low,margin_up,length,id,resultat
0,171.76,104.01,103.54,5.21,3.30,111.42,A_1,False
1,171.87,104.17,104.13,6.00,3.31,112.09,A_2,False
2,172.00,104.58,104.29,4.99,3.39,111.57,A_3,False
3,172.49,104.55,104.34,4.44,3.03,113.20,A_4,True
4,171.65,103.63,103.56,3.77,3.16,113.33,A_5,True